[package]
name = "password-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.15"
rand = "0.8.4"
aes = "0.8.2"
block-modes = "0.7.0"


